# Generated by Django 5.1.4 on 2024-12-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidades', models.TextField()),
                ('tipo_conteudo', models.TextField()),
                ('grupos_estudo', models.TextField()),
                ('biblioteca_recursos', models.TextField()),
                ('tutorias_online', models.TextField()),
                ('integracao', models.TextField()),
                ('funcionalidades_moveis', models.TextField()),
                ('usabilidade', models.TextField()),
                ('interacao', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
